<?php

namespace common\models\system\classifier;

use yii\db\Expression;
use yii\helpers\ArrayHelper;

class MasterSpeciality extends BachelorSpeciality
{
    public static function tableName()
    {
        return 'h_master_speciality';
    }

    private static function updateParent($model)
    {
        $code = mb_substr($model->code, 2, 2);
        if ($parent = self::findOne(['code' => $code . '0000'])) {
            if ($parent->code != $model->code) {
                $model->updateAttributes(['_parent' => $parent->code]);
            }
        }
    }

    public function beforeSave($insert)
    {
        $this->code = str_replace('А', 'A', $this->code);

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function getParentItem()
    {
        $code = mb_substr(trim($this->code), 2, 2) . '0000';
        if ($parent = self::findOne(['code' => $code])) {
            if ($parent->code != $this->code) {
                return $parent;
            }
        }

        return null;
    }

}